---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: wego-246d555a683efaadbe37fe063a1990c6
  name: podinfo-deploy
  namespace: wego-system
spec:
  deployment_type: kustomize
  path: ./
  url: ssh://git@github.com/wkp-example-org/podinfo-deploy.git
