---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sample-app
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/palemtnrider/podinfo-deploy.git

